### ISSUE TITLE
pagure auth fails if token file contains trailing newline

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/alt-src#38]
If the API token file used to communicate with pagure contains a trailing newline, it seems that requests to pagure will be rejected with a 400 response.

Since it is very common and sometimes considered best practice to end files with a trailing newline, and since the error is quite confusing, it'd be nice to fix this.  For example, `strip()` the loaded token to remove any trailing whitespace before using it in the authorization failure.

When a failure occurs due to this, it looks like:

```
2020-08-10 13:04:22,131 [INFO] Creating pagure repo:: {'wait': True, 'namespace': 'rpms', 'name': 'grub2', 'private': False, 'description': 'Bootloader with support for Linux, Multiboot and more'}
2020-08-10 13:04:22,156 [ERROR] Staging failed
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/alt_src/alt_src.py", line 2212, in main
    task.run()
  File "/usr/lib/python2.6/site-packages/alt_src/alt_src.py", line 1712, in run
    self.push_git(state)
  File "/usr/lib/python2.6/site-packages/alt_src/alt_src.py", line 1811, in push_git
    self.init_pagure_remote_repo()
  File "/usr/lib/python2.6/site-packages/alt_src/alt_src.py", line 1939, in init_pagure_remote_repo
    resp = urlopen(req)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request
```

**Comment by rbikar** [comment]
Fixed by https://github.com/release-engineering/alt-src/pull/58
